version: '3'

services:
  streamlit:
    build: ./
    restart: always
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: spotify-streamlit

networks:
  deploy_network:
    driver: bridge
